development:
  adapter: postgresql
  encoding: utf8
  database: brain_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: brain_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: brain_production
  pool: 5
  username:
  password:
